version: "3.3"

services:
  kg_lc:
    container_name: kg_lc
    image: prohde/virtuoso-opensource-7:7.2.11
    ports:
      - "8891:8890"
    volumes:
      - ./experiments_kg_builder/nt/LungCancer.nt:/database/toLoad/LungCancer.nt
    networks:
      - semdeslc

  kg_semdeslc:
    container_name: kg_semdeslc
    image: prohde/virtuoso-opensource-7:7.2.11
    ports:
      - "8892:8890"
    volumes:
      - ./experiments_kg_builder/nt/SemDesLC.nt:/database/toLoad/SemDesLC.nt
    networks:
      - semdeslc

  rules:
    build: ./SymbolicLearning
    image: semdeslc:rules
    container_name: rules
    volumes:
        - ./SymbolicLearning/Rules/data:/Rules/data
        - ./SemDesLC/rules:/result
  
  streamlit:
    build: .
    image: semdeslc:interface
    container_name: semdeslc
    ports:
      - "8501:8501"
    volumes:
      - ./images:/app/images
      - ./SemDesLC/shapes:/app/shapes
      - ./SemDesLC/rules:/app/rules
      - ./SemDesLC/files:/app/files
      - ./SemDesLC/output:/app/output
      - ./:/app/example
    command: ["streamlit", "run", "app.py"]
    networks:
      - semdeslc
    depends_on:
      - rules
      - kg_lc
      - kg_semdeslc
      
networks:
  semdeslc:
    driver: bridge
